version: "3.8"

networks:
  dev-network:
    driver: bridge

services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  booking-logging-service:
    container_name: "Booking.RideLoggingService"
    build:
      context: .
      dockerfile: Booking.RideLoggingService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8083:8080"
    depends_on:
      - "rider-db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=rider-db;Database=booking_logging_db;Username=postgres;Password=admin@123
    networks:
      - dev-network
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  booking-booking-service:
    container_name: "Booking.RideBookingService"
    build:
      context: .
      dockerfile: Booking.RideBookingService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8081:8080"
    depends_on:
      - "rider-db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=rider-db;Database=booking_book_db;Username=postgres;Password=admin@123
    networks:
      - dev-network
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  booking-rider-service:
    container_name: "Booking.RiderService"
    build:
      context: .
      dockerfile: Booking.RiderService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8082:8080"
    depends_on:
      - "rider-db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=rider-db;Database=booking_rider_db;Username=postgres;Password=admin@123
    networks:
      - dev-network
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  
  rider-db:
    container_name: "RideBooking.Database.Postgres"
    image: "postgres:alpine"
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin@123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  postgres-data:
