// <auto-generated />
using System;
using CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(CustomerServiceDbContext))]
    [Migration("20240205091809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Models.RiderRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmdatetime");

                    b.Property<Guid>("Customer")
                        .HasColumnType("uuid")
                        .HasColumnName("customer");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("isconfirmed");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestdatetime");

                    b.Property<DateTime>("RequestedForDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedfordatetime");

                    b.HasKey("Id")
                        .HasName("pk_riderrequests");

                    b.ToTable("riderrequests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
